
server:
  port: 9090

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: User
          uri: lb://User
          predicates:
            - Path=/user/**
        - id: Department
          uri: lb://Department
          predicates:
            - Path=/department/**
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost