spring:
  application:
    name: department-service
  zipkin:
    base-url: http://127.0.0.1:9411/

server:
  port: 8065

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url.defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost